riego/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('riegoApp.urls', namespace='riego')),
    path('admin/', admin.site.urls),
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('docs/', include('docs.urls')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

riegoApp/urls.py
from django.urls import path, include
from django.conf.urls import url
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import login, logout_then_login
from . import views, servicios

from riegoApp.views import index, ChartView

app_name = 'riegoApp'

urlpatterns = [
    url(r'^index/$',  login_required(index), name='index'),
    url(r'^accounts/login',login,{'template_name':'login.html'}, name="login"),
    url(r'^logout/',logout_then_login,name="logout"),
    url(r'^chart/',ChartView.as_view(),name="chart"),
    url(r'^reporte/',servicios.reportes,name="report"),
    url(r'^ambientes/',servicios.LlenarAmbientes,name="ambientes"),
    url(r'^sensores/',servicios.LlenarSensores,name="sensores"),
    path('guardarDatos/',servicios.guardarDatosSensor,name='guardar-datos'),
    
]

riegoApp/models.py
from django.contrib.auth.models import User
from django.db import models
#from django.contrib.gis.db import models
# Create your models here.


class Distritos(models.Model):
    """
    Stores a single blog entry, related to :model:`riegoApp.Blog` and
    :model:`auth.User`.
    """
    nombre = models.CharField(max_length=50)

    class Meta:
        verbose_name = 'Distrito'
        verbose_name_plural = "Distritos"

    def __str__(self):
        return self.nombre
    
class Sectores(models.Model):
    """
    Guarda una relacion con :model:`riegoApp.Distritos` y 
    el nombre del distrito
    """
    distrito = models.ForeignKey(Distritos, related_name='distrito', on_delete=models.CASCADE)
    nombre = models.CharField(max_length=50)

    class Meta:
        verbose_name = 'Sector'
        verbose_name_plural = "Sectores"

    def __str__(self):
        return  self.distrito.nombre + " - " + self.nombre

class Ambiente(models.Model):
    """
    Guarda una relacion con :model:`riegoApp.Sectores` y 
    una descripcion del ambiente y la densidad de plantas que existe
    """
    sector = models.ForeignKey(Sectores, related_name='sectores', on_delete=models.CASCADE)
    descripcion = models.CharField(max_length=50)
    densidad = models.FloatField(default = 0)

    class Meta:
        verbose_name = 'Ambiente'
        verbose_name_plural = "Ambientes"
    

class Sensor(models.Model):
    """
    Guarda una relacion con :model:`riegoApp.Ambiente`,
    la fecha de cuando a sido instalado, dos estados( activo, inactivo),
    y la latitud y longitud, para saber donde esta ubicado
    """
    ambiente = models.ForeignKey(Ambiente, related_name='sensor', on_delete=models.CASCADE)
    fecha = models.DateTimeField(auto_now=True)
    ACTIVO = 1
    INACTIVO = 2
    ESTADOS = (
        (ACTIVO, 'Activo'),
        (INACTIVO, 'Inactivo'),
    )
    estado = models.IntegerField(choices=ESTADOS, default=ACTIVO)
    latitud = models.FloatField(default=0)
    longitud = models.FloatField(default=0)
    #mpoly = models.MultiPolygonField()

    class Meta:
        verbose_name = 'Sensor'
        verbose_name_plural = "Sensores"
    

class Detalle_Sensor(models.Model):
    sensor = models.ForeignKey(Sensor ,related_name='sensor_detalle', on_delete=models.CASCADE)
    humedad = models.IntegerField(default=0)
    fecha = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'Detalle del sensor'
        verbose_name_plural = "Detalle de los sensores"
    

class Riego(models.Model):
    fechaInicio = models.DateTimeField(auto_now_add=True)
    fechaFin = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'Riego'
        verbose_name_plural = "Riego"

class Arduino(User):
    sensor = models.ForeignKey(Sensor, related_name='sensor', on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Arduino'
        verbose_name_plural = "Arduino"

class Reportes(models.Model):
    #arduino = models.ForeignKey(Arduino, related_name='arduino', on_delete=models.CASCADE)
    fecha = models.DateField(auto_now_add=True)
    #riego = models.ForeignKey(Riego, related_name='riego', on_delete=models.CASCADE)
    reporte = models.FileField(upload_to='reportes', blank=True, null=True, default="")

    class Meta:
        verbose_name = 'Reporte'
        verbose_name_plural = "Reportes"

riegoApp/views.py
from django.shortcuts import render
from django.template.loader import get_template
from django.http import HttpResponse
from django.views.generic import View
# Create your views here.
from riegoApp.models import *
from django.db.models.functions import Extract
from django.db.models import Count, Sum
from django.db.models.functions import TruncYear, TruncMonth



def index(request):
    t = get_template('index.html')
    d = Distritos.objects.get(pk = 1)
    html = t.render({'distrito':d}, request)

    return HttpResponse(html)


class ChartView(View):
    def get(self, request, *args, **kwargs):
        t = get_template('chart.html')
        filtro = self.request.GET['filtro']
        if filtro == '0':
            tipoFecha = self.request.GET['tipo']
            if tipoFecha == '0': #ANIO
                detalle = Detalle_Sensor.objects \
                    .annotate(date=TruncYear('fecha'))\
                    .values('date')\
                    .annotate(humedad=Sum('humedad'),c=Count('id'))\
                    .values('date', 'humedad','c')
                
            elif tipoFecha == '1':
                detalle = Detalle_Sensor.objects \
                    .annotate(date=TruncMonth('fecha'))\
                    .values('date')\
                    .annotate(humedad=Sum('humedad'),c=Count('id'))\
                    .values('date', 'humedad','c').filter(fecha__year='2018')
            
            contexto = {"detalle": detalle,"tipo":tipoFecha}

        else:
            ambiente = self.request.GET['ambiente']
            sensor = self.request.GET['sensor']
            if (sensor == '-1'):
                ambiente = Ambiente.objects.get(pk = ambiente)
                sensores = ambiente.sensor.all()
            
                detalle = Detalle_Sensor.objects \
                    .annotate(date=TruncMonth('fecha'))\
                    .values('date')\
                    .annotate(humedad=Sum('humedad'),c=Count('id'))\
                    .values('date', 'humedad','c').filter(fecha__year='2018',sensor__in = sensores).order_by('fecha')
            else:

                detalle = Detalle_Sensor.objects \
                    .annotate(date=TruncMonth('fecha'))\
                    .values('date')\
                    .annotate(humedad=Sum('humedad'),c=Count('id'))\
                    .values('date', 'humedad','c').filter(fecha__year='2018',sensor = sensor).order_by('fecha')



            contexto = {"detalle": detalle}
        
        html = t.render(contexto)
        return HttpResponse(html)





    

riegoApp/templates/chart.html
<canvas id="chart" ></canvas>

{% block javascript %}
{% load static %}
<script src="{% static 'vendor/chart.js/Chart.min.js' %}"></script>

<script>

    // Set new default font family and font color to mimic Bootstrap's default styling
Chart.defaults.global.defaultFontFamily = '-apple-system,system-ui,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Arial,sans-serif';
Chart.defaults.global.defaultFontColor = '#292b2c';

// Area Chart Example
var ctx = document.getElementById("chart");
var myLineChart = new Chart(ctx, {
  type: 'line',
  data: {
    labels: [

        {% if tipo == '0' %}
            {% for d in detalle %}
                '{{d.date|date:"Y"}}',
            {% endfor %}

        {% else %}

            {% for d in detalle %}
                '{{d.date|date:"M"}}',
            {% endfor %}
        {% endif %}
    ],
    datasets: [{
      label: "Humedad",
      lineTension: 0.3,
      backgroundColor: "rgba(2,117,216,0.2)",
      borderColor: "rgba(2,117,216,1)",
      pointRadius: 5,
      pointBackgroundColor: "rgba(2,117,216,1)",
      pointBorderColor: "rgba(255,255,255,0.8)",
      pointHoverRadius: 5,
      pointHoverBackgroundColor: "rgba(2,117,216,1)",
      pointHitRadius: 50,
      pointBorderWidth: 2,
      data: [
        {% for d in detalle %}
          '{{d.humedad}}',
        {% endfor %}
      ],
    }],
  },
  options: {
    scales: {
      xAxes: [{
        time: {
          unit: 'date'
        },
        gridLines: {
          display: false
        },
        ticks: {
          maxTicksLimit: 7
        }
      }],
      yAxes: [{
        ticks: {
          min: 0,
          max: 100,
          maxTicksLimit: 5
        },
        gridLines: {
          color: "rgba(0, 0, 0, .125)",
        }
      }],
    },
    legend: {
      display: false
    }
  }
});


</script>
{% endblock javascript %}

riegoApp/templates/index.html
{% extends "base.html" %}

{% block style %}
      
<style>
    iframe#someFrame{
        border-width: 0px;
        border-style: inset;
        border-color: initial;
        border-image: initial;
        margin-top: -20px;
    }

    .hidden {
        display: none;
    }
</style>
  {% endblock style %}

{% block content %}
<ol class="breadcrumb">
    <li class="breadcrumb-item">
        <a href="{% url "riegoApp:index" %}">Dashboard</a>
    </li>
    <li class="breadcrumb-item active">Blank Page</li>
</ol>

<div class="card mb3">
    <div class="card-header">
        <i class="fas fa-info"></i>
        
    </div>
</div>

<div class="card mb-3">
  <div class="card-header">
    <i class="fas fa-chart-area"></i>
    Grafica de humendad del distrito de {{distrito}}</div>
  <div class="card-body">
      <label for="exampleFormControlSelect1">Filtrar por: </label>
      <select class="form-control" id="filtro">
          <option value="0">Fecha</option>
          <option value="1">Ambiente</option>
      </select>

      <label for="exampleFormControlSelect1">Ver Grafico por: </label>
      <select class="form-control" id="tipo">
          <option value="0">Años</option>
          <option value="1">Ultimo año</option>
      </select>

      <div class="sensor hidden">

          <label for="exampleFormControlSelect1">Seleccionar Sensor </label>
          <select class="form-control" id="sensor">
              <option value="0">Años</option>
              <option value="1">Ultimo año</option>
          </select>
      </div>
      <br>
    <iframe name="someFrame" id="someFrame" height="550px" width="100%"></iframe>
    
    <button class="btn btn-primary btn-block" id="reporte">Descargar Reporte</button>
  </div>
    <!-- <div class="card-footer small text-muted">Updated yesterday at 11:59 PM</div> -->
</div>


  <div class="modal fade" id="reporte" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Descargar reporte</h5>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body">

        </div>
        <div class="modal-footer">
          <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
          <a class="btn btn-primary" href="{% url "riegoApp:report"  %}">Descargar</a>
        </div>
      </div>
    </div>
  </div>


{% endblock content %}

{% block javascript %}

<script>
var url = '{% url 'riego:chart' %}' 
  $( document ).ready(function() {

    $.get(url,{filtro:0,tipo:0})
      .done(response => {
          document.getElementById("someFrame").html = response;
          $("#someFrame").attr("srcdoc", response);
      })

    

    $("#tipo").on('change', function () {        
        var b = $("#tipo option:selected").val()
        var f = $("#filtro option:selected").val()
        if (f == '0'){
            $.get(url,{tipo:b,filtro:f})
            .done(response => { 
                document.getElementById("someFrame").html = response;
                $("#someFrame"  ).attr("srcdoc", response);
            })
        }
        else{
            llenarSensores(b)
            $.get(url,{tipo:b,filtro:f,ambiente:b,sensor:'-1'})
            .done(response => { 
                document.getElementById("someFrame").html = response;
                $("#someFrame"  ).attr("srcdoc", response);
            })
        }
    });

  })

    $("#filtro").on('change',function(){
        var v = $("#filtro option:selected").val()
        llenarAmbientes(v)
    })

    $("#sensor").on('change',function(){
        var b = $("#tipo option:selected").val()
        var f = $("#filtro option:selected").val()
        var s = $("#sensor option:selected").val()

        $.get(url,{tipo:b,filtro:f,ambiente:b,sensor:s})
        .done(response => { 
            document.getElementById("someFrame").html = response;
            $("#someFrame"  ).attr("srcdoc", response);
        })

    })
    

    function llenarAmbientes(value){

        var url = '{% url 'riego:ambientes' %}'
        var Options
        let $el = $("#tipo");

        $el.empty(); // remove old options

        if (value == '0'){
            Options = {
                "Años": "0",
                "Ultimo Año": "1",
            };
            $.each(Options, function(key,value) {
                $el.append($("<option></option>")
                .attr("value", value).text(key));
            });
            $(".sensor").addClass('hidden')
        }else{
            $.get(url)
            .done(response => {
                $.each(response,function(index,value){
                    var desc = value.desc
                    var pk = value.pk
                    $el.append($('<option>', { 
                        value: pk,
                        text : desc
                    }));

                })

                $(".sensor").removeClass('hidden')
                var a = $("#tipo option").eq(0).val()
                llenarSensores(a)
            })
        }

    }


    function llenarSensores(a){

        var url = '{% url 'riego:sensores' %}'
        var Options
        let $sen = $("#sensor");

        $sen.empty(); // remove old options
        
        Options = {
            "Todos": "-1",
        };
        $.each(Options, function(key,value) {
            $sen.append($("<option></option>")
            .attr("value", value).text(key));
        });

        $.get(url, {ambiente:a})
        .done(response => {
            $.each(response,function(index,value){
                var desc = value.desc
                var pk = value.pk
                $sen.append($('<option>', { 
                    value: pk,
                    text : desc
                }));

            })
        })
    }

</script>


<script>


    $("#reporte").on('click',function(){
        reporte()
    })
    function reporte(){
        var url = "{% url 'riegoApp:report'  %}"
        var b = $("#tipo option:selected").val()
        var f = $("#filtro option:selected").val()
        var s = $("#sensor option:selected").val()

        $.get(url,{tipo:b,filtro:f,ambiente:b,sensor:s})
        .done(response => { 
            window.open(response,'_blank');
        })

    }

</script>

{% endblock javascript %}

templates/base.html
<!DOCTYPE html>
<html lang="en">

  <head>
    {% load static %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Sistema de Riego</title>

    <!-- Bootstrap core CSS-->

    
    {% block style %}
      
    {% endblock style %}
      
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/datatables/dataTables.bootstrap4.css' %}" rel="stylesheet">
    <link href="{% static 'css/sb-admin.css' %}" rel="stylesheet">

    <!-- Custom fonts for this template-->

    <!-- Page level plugin CSS-->

    <!-- Custom styles for this template-->
    

  </head>

  <body id="page-top">

    <nav class="navbar navbar-expand navbar-dark bg-dark static-top">

      <a class="navbar-brand mr-1" href="#">Sistema de Riego</a>

      <button class="btn btn-link btn-sm text-white order-1 order-sm-0" id="sidebarToggle" href="#">
        <i class="fas fa-bars"></i>
      </button>

      <!-- Navbar Search -->
    
      <form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
        {% comment %} 
        <div class="input-group">
          <input type="text" class="form-control" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
          <div class="input-group-append">
            <button class="btn btn-primary" type="button">
              <i class="fas fa-search"></i>
            </button>
          </div>
        </div> 
        {% endcomment %}
      </form>

      
      <ul class="navbar-nav ml-auto ml-md-0">
        <li class="nav-item dropdown no-arrow">
          <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fas fa-user-circle fa-fw"></i>
          </a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
            <a class="dropdown-item" href="#">Settings</a>
            <a class="dropdown-item" href="#">Activity Log</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">Logout</a>
          </div>
        </li>
      </ul> 

    </nav>

    <div id="wrapper">
      <!-- Sidebar -->
      <ul class="sidebar navbar-nav">
        <li class="nav-item active">
          <a class="nav-link" href="index.html">
            <i class="fas fa-fw fa-tachometer-alt"></i>
            <span>Dashboard</span>
          </a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="pagesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fas fa-fw fa-folder"></i>
            <span>Pages</span>
          </a>
          <div class="dropdown-menu" aria-labelledby="pagesDropdown">
            <h6 class="dropdown-header">Login Screens:</h6>
            <a class="dropdown-item" href="{% url 'riegoApp:login'  %}">Login</a>
            <a class="dropdown-item" href="register.html">Register</a>
            <a class="dropdown-item" href="forgot-password.html">Forgot Password</a>
            <div class="dropdown-divider"></div>
            <h6 class="dropdown-header">Other Pages:</h6>
            <a class="dropdown-item" href="404.html">404 Page</a>
            <a class="dropdown-item" href="blank.html">Blank Page</a>
          </div>
        </li>
        <li class="nav-item">
            <!-- <a class="nav-link" href="{% url 'riegoApp:report' %}">
              <i class="fas fa-file-alt"></i>
            </a> -->
          <a class="nav-link" href="#" data-toggle="modal" data-target="#reporte">
            <i class="fas fa-file-alt"></i>
            <span>Descargar reportes</span>
          </a>
        </li>
      </ul>

      <div id="content-wrapper">

        <div class="container-fluid">
          
          {% block content %}
          
          <!-- Breadcrumbs-->
          <ol class="breadcrumb">
            <li class="breadcrumb-item">
              
              <a href="{% url "riegoApp:index" %}">Dashboard</a>
            </li>
            <li class="breadcrumb-item active">Blank Page</li>
          </ol>
          
          <!-- Page Content -->
          <h1>Blank Page</h1>
          <hr>
          <p>This is a great starting point for new custom pages.</p>
          
          {% endblock content %}

        </div>

        
        {% block footer %}
          
        
        <!-- Sticky Footer -->
        <footer class="sticky-footer">
          <div class="container my-auto">
            <div class="copyright text-center my-auto">
              <span>Copyright © Uls</span>
            </div>
          </div>
        </footer>
        
        {% endblock footer %}
      </div>
      <!-- /.content-wrapper -->

    </div>
    <!-- /#wrapper -->

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
      <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
            <button class="close" type="button" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">×</span>
            </button>
          </div>
          <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
          <div class="modal-footer">
            <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
            <a class="btn btn-primary" href="{% url "riegoApp:logout"  %}">Logout</a>
          </div>
        </div>
      </div>
    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>


    <!-- Core plugin JavaScript-->
    <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

    <!-- Page level plugin JavaScript-->
    <script src="{% static 'vendor/chart.js/Chart.min.js' %}"></script>
    <script src="{% static 'vendor/datatables/jquery.dataTables.js' %}"></script>
    <script src="{% static 'vendor/datatables/dataTables.bootstrap4.js' %}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{% static 'js/sb-admin.min.js' %}"></script>

    <!-- Demo scripts for this page-->
    <script src="{% static 'js/demo/datatables-demo.js' %}"></script>
    <script src="{% static 'js/demo/chart-area-demo.js' %}"></script>
    
    {% block javascript %}
      
    {% endblock javascript %}
      
  </body>

</html>

templates/login.html
<!DOCTYPE html>
<html lang="en">

  <head>
    {% load static %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>SB Admin - Login</title>

    <!-- Bootstrap core CSS-->

    <!-- Custom fonts for this template-->

    <!-- Custom styles for this template-->

    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/sb-admin.css' %}" rel="stylesheet">

  </head>

  <body class="bg-dark">

    <div class="container">
      <div class="card card-login mx-auto mt-5">
        <div class="card-header">Login</div>
        <div class="card-body">
          <form id="login-form" method="post" action="{% url "riegoApp:login"  %}">
              {% csrf_token %}
            <div class="form-group">
              <div class="form-label-group">
                <input type="text" class="form-control" aria-describedby="emailHelp" name="username" autofocus="" maxlength="254" required="" id="id_username" placeholder="Nombre de usuario">
                <label for="id_username">Username</label>
              </div>
            </div>
            <div class="form-group">
              <div class="form-label-group">
                  <input type="password" class="form-control" placeholder="Contraseña" name="password" required="" id="id_password">
                <label for="id_password">Password</label>
              </div>
            </div>
            {% if form.errors %}
                <p class=" label label-danger">
                    El usuario y/o la contraseña no coinciden.
                    Intentelo nuevamente
                </p>
              {% endif %}
            <button class="btn btn-primary btn-block">Login</button>
          </form>
        </div>
      </div>
    </div>

    <!-- Bootstrap core JavaScript-->

    <!-- Core plugin JavaScript-->



        <!-- Bootstrap core JavaScript-->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>


    <!-- Core plugin JavaScript-->
    <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

  </body>

</html>